on join:
    wait 10 ticks
    give player 1 book named "§cРежимы" with lore "§7ПКМ для открытия меню"

# Видача книги при респавні
on respawn:
    wait 10 ticks
    give player 1 book named "§cРежимы" with lore "§7ПКМ для открытия меню"

# Відкриття меню книгою
on right click with book:
    if name of player's tool contains "Режим":
        cancel event
        make player execute command "/menu"